### ISSUE TITLE
Permit cross-domain framing

### ISSUE THREAD

**Issue by sudosammy** [motor-admin/motor-admin#104]
Hey, I love the project and have been using it for a while, but it's unfortunate you can't `iframe` motoradmin pages cross-domain because of the restrictive `X-Frame-Options: SAMEORIGIN` header set on every page.

I couldn't see an easy way to configure this (i.e. remove it) so that I can frame motoradmin pages cross-domain. Could this header (and other headers ideally) be toggleable/configurable instead?

The risk of clickjacking is outside of the threat model I care about.

Thanks for the hard work!

**Comment by omohokcoj** [comment]
@sudosammy i tried to add 'X-Frame-Options' => 'ALLOWALL'  but it doesn't solve the issue completely
https://github.com/motor-admin/motor-admin/commit/ba7ba42897d805607d951c6f3e327a781485a757

Motor Admin requires authentication - so you'll need to sign in with email and password in iframe.
And the problem is that the sign in form is protected with CSRF - unfortunately i was not able to find a way to make it work in iframe.

I think a popper solution for this issue would be to create shareable token protected report/dashboard links that can be embeded in iframe without authorization - maybe that's something that will be implemented in the future if we see more users need this feature

**Comment by sudosammy** [comment]
Ah right, I see. Yeah that's a shame. My use case is integrating parts of motor admin into an existing CRM panel. So I was hoping to iframe particular views/functionality. Will need to come up with a new solution there.
