### ISSUE TITLE
Create class-level custom actions, not just instance level

### ISSUE THREAD

**Issue by vince-platform45** [motor-admin/motor-admin#30]
Custom actions can currently only be defined (as far as I can see) on existing instances (or rows in the database, if you prefer).

This prevents several very common use cases for custom actions - as an example, if we have a user model that allows for the invitation of new users, that action can only be invoked from the context of a current user... Something that is obviously entirely non-sensical. This kind of action would live at the same level as eg the new or create action.

If this functionality already exists, I apologise, but I have not been able to find it.

**Comment by omohokcoj** [comment]
@vince-platform45 makes sense, so the issue is that it's impossible to add an action button on the same level with new/create action button:
<img width="1536" alt="image" src="https://user-images.githubusercontent.com/5418788/146512304-9103cf0b-117f-442f-8228-a1d3c3a8fc3b.png">
It's possible to create a custom form and invoke it from the forms list or via quick search feature.
There won't be enough space for buttons on the resource table page but maybe some dropdown with actions could work.
I'll check what can be done there, thanks for the feedback!

**Comment by omohokcoj** [comment]
@vince-platform45 the latest version allows to mark actions as 'on collection' so they will be displayed on Resources table dropdown instead of the individual resource page - hope this solves the issue.
