### ISSUE TITLE
Security Issues

### ISSUE THREAD

**Issue by hagaiwech** [motor-admin/motor-admin#35]
Hi motor-admin team,
I've tried to contact you through mail, but received no response.
I'm approaching you regarding security issues found in your project.

Please contact me through mail, to this address: hagai.wechsler@whitesourcesoftware.com
Thanks

**Comment by omohokcoj** [comment]
@hagaiwech I received your email a couple of weeks ago and the vulnerability provided in your report was only possible with motor admin development setup.
It was impossible to reproduce it in production setup when motor admin is hosted on heroku or in docker/kubernetes under domain name and ssl - nonetheless, that vulnerability has been fixed in motor admin master branch.

Anyways I appreciate they way how your company markets its services - wishing your company an exciting growth!

**Comment by hagaiwech** [comment]
@omohokcoj Thanks for getting back to me!
We will look into your claims and update you ASAP.
Meanwhile, can you send us the commit link that fixes these vulnerabilities?
You can send it to hagai.wechsler@whitesourcesoftware.com if you'd like to keep it private.
