### ISSUE TITLE
Downloading file from custom form

### ISSUE THREAD

**Issue by jakubjanousek** [motor-admin/motor-admin#63]
We would like a custom endpoint in our API that would return a CSV file based on parameters being sent (startDate, endDate).

Is there a way to connect such an endpoint through the MotorAdmin form? If we send the form through a POST request, the CSV is just displayed instead of being downloaded

The current API code is the following:
```
      const csvString = await getReportCsvString(startDate, endDate)
      res.status(200).attachment('report.csv').send(csvString)
      res.sendStatus(200)
```

**Comment by omohokcoj** [comment]
@jakubjanousek it has been fixed in the new 0.3.10 release (as well as in Pro/Enterprise).
It uses https://developer.mozilla.org/ru/docs/Web/HTTP/Headers/Content-Disposition to determine if that attachment should be downloaded. I think `.attachment('report.csv')` sets Content-Disposition header so it should work with your api code as is.
