### ISSUE TITLE
How to show data in Select field of form after calling from API

### ISSUE THREAD

**Issue by futurescape-tech** [motor-admin/motor-admin#74]
Hi,

With the use of Motor Admin, we've created some queries which calls of custom API path and gets desired result in table format. Now, we want to show the same result in Select input field of another form, but getting "no result".

Secondly, can we create a Country, state, city dependency flow using Motor Admin as conditions can not be set dynamically.

In both the cases, we may not have researched enough as we are new in using this tool. We found this very useful but falling in some cases. It would be more helpful if you let us know the exact flow.

Thanks in advance.

**Comment by omohokcoj** [comment]
@futurescape-tech 

>With the use of Motor Admin, we've created some queries which calls of custom API path and gets desired result in table format. Now, we want to show the same result in Select input field of another form, but getting "no result".

Thanks for reporting this bug - it has been fixed in the latest 0.4.4 docker image.

>Secondly, can we create a Country, state, city dependency flow using Motor Admin as conditions can not be set dynamically.

It seems like you wanted to have your form selector options changed based on the value selected in some other field (for example City selector options change to only Cities in California state when the state is selected)
It's possible to achieve this by using query valuables - form values are passed to the selector query implicitly - so if your "Cities" query contains "state_id" filter variable then the selector options will be reloaded with this value each time your "state_id" field on the form changes. Hope this helps to resolve the issue.
