### ISSUE TITLE
Version 0.3.16 configured as latest

### ISSUE THREAD

**Issue by notfounnd** [motor-admin/motor-admin#76]
I've tried update my motor admin instance and seen the tool not change up to version 0.4.3.

I checked the repo and that binary files hasn't been generated at 0.4.4 and 0.4.5 versions.

**Comment by omohokcoj** [comment]
@notfounnd unfortunately i stopped providing binary releases for motor-admin starting from 0.4.0 version (required more time to maintain).
So new versions are available only in docker images.
So instead of the binary you can simply run `docker run -it -p 3000:3000 -v `pwd`:/app motoradmin/motoradmin:latest` from the same folder you used to run the binary.

**Comment by notfounnd** [comment]
@omohokcoj wonder, I'll provide changes here in my env. Thanks dude! o/

**Comment by agentcobra** [comment]
Hi
How can we compile the binary ?

**Comment by omohokcoj** [comment]
@agentcobra unfortunately there are no easy ways to compile the latest version into a binary.
The compiler https://github.com/motor-admin/ruby-packer is ruby 3.1 version but the latest release uses 3.2 - also some patches for the binary release have been already removed from the codebase.

Basically I just found docker more convenient than the binary - easier to run and update to new versions. If you have some particular issues with the docker setup i'd be happy to help to resolve those.
