### ISSUE TITLE
Link to child resource in single table inheritance

### ISSUE THREAD

**Issue by antran511** [motor-admin/motor-admin#98]
Hi,

I have a use case where I want to link to my child class instead of parent class. Let's say I have 2 types product `A` and `B` that inherited from table `Item`. For any record that reference to `Item`, I want the reference link go to `www.host.com/A/1`instead of `www.host.com/item/1`. 

Is there any way I can achieve that?
Thank you

**Comment by omohokcoj** [comment]
@antran511 if your 'product' A/B are separate tables - then you can create a 'polymorphic' association with those records.
So let's say you have an 'Order' resource and 'order' has many 'items' (items could be from table A or from Table B).
In this case you can use a polymorphic association so that references to "Item" link to /a or /b based on the item resource/type
<img width="712" alt="image" src="https://github.com/motor-admin/motor-admin/assets/5418788/2f1e4ff7-3647-476a-b23f-4aeee5f1ae6f">
